- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      yum: 
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/ansible_setup/create_ansible_user.yml
    - include: tasks/ansible_setup/add_lib_to_sudoers_path.yml
    - include: tasks/packages/install_prerequired_package.yml

      #- include: tasks/ec2_setup/create_swap_memory.yml
      #vars:
      #  swap_size: 24

      #- include: tasks/packages/install_prerequired_package.yml
      #- include: tasks/users/create_user.yml
      #vars:
      #  username: cog117cm
      #- include: tasks/users/create_user.yml
      #vars:
      #  username: cog117as
      #- include: tasks/installation/install_binaries_AS.yml
