- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      apt: 
        update_cache: yes
      changed_when: false

  tasks:
    #- include: tasks/ansible_setup/create_ansible_user.yml 
    #- include: tasks/ansible_setup/install_cron_package.yml
    #- include: tasks/ansible_setup/add_ansible_to_cron.yml
    #- include: tasks/packages/install_prerequired_package.yml
    #- include: tasks/installation/install_binaries.yml
    - include: tasks/ec2_setup/set_ulimits.yml
      vars:
        user: "root" 
    #
    #    install_binaries.yml
