- hosts: localhost
  connection: local
  become: true
  vars:
    - component_type: "CM"
    - inst_user: "cog117cm"
    - super_user: "root"
  tasks:
    # Add /usr/local/lib to path for sudo
    #- include: tasks/ansible_setup/add_lib_to_sudoers_path.yml
    
    #
    - include: tasks/ansible_setup/create_ansible_user.yml
    
    # Install base packages
    - include: tasks/packages/install_prerequired_package.yml
    
    #
    - include: tasks/users/create_user.yml
      vars:
        username: "{{ inst_user }}"
    
    #
    - include: tasks/ec2_setup/set_ulimits.yml
      vars:
        - user: "{{ super_user}}"
        - nofile_limit_for: "{{ inst_user }}"
    
    #
    - include: tasks/installation/install_binaries_CM.yml
      vars:
        - root_folder: "/opt"
        - app_folder: "{{ root_folder }}/appl"
        - sources_folder: "{{ app_folder }}/sources"
        - drivers_folder: "{{ app_folder }}/{{ inst_user }}/drivers"
        - configuration_folder: "{{ app_folder }}/{{ inst_user }}/configuration"
        - s3_bucket_with_sources: "s3://cognos-dev-s3-management/Cognos-src"
        - s3_bucket_configuration_files: "{{ s3_bucket_with_sources }}/ConfigFiles"