- name: Playbook to apply templates
  hosts: localhost
  connection: local
  become: true
  vars:
    - _env: "production"
    - env: "dev"
    - a: "test"


  tasks:
    - name: Play for testing scripts before move them to final files
      ansible.builtin.command: echo "Hello"
      register: my_output
      changed_when: my_output.rc != 0

    - name: Call template include
      ansible.builtin.include_tasks: tasks/installation/apply_template.yml
      vars:
        - DISPATCHER_PORT: 9300
        - EXTERNAL_DISPATCHER_URI: 'http://ip-10-56-3-137.eu-west-1.compute.internal:{{ DISPATCHER_PORT }}/p2pd/servlet/dispatch' #- Line 193
        - INTERNAL_DISPATCHER_URI: 'http://ip-10-56-3-137.eu-west-1.compute.internal:{{ DISPATCHER_PORT }}/p2pd/servlet/dispatch' #- Line 205
        - DISPATCHER_URI_4_EXTERNAL_APPS: 'http://ip-10-56-3-137.eu-west-1.compute.internal:{{ DISPATCHER_PORT }}/bi/v1/disp' #- Line 285
        - CONTENT_MANAGER_URI: 'http://internal-creport-dev-lb-content-mgr-1585325614.eu-west-1.elb.amazonaws.com:{{ DISPATCHER_PORT }}/p2pd/servlet' #- Line 295
        - GROUP_NAME: 'GRP_CREPORTDEV' #- Line 359 ( we can parameterize with environment - creport-dev)
        - GROUP_CONTACT_HOST: 'ip-10-56-3-133.eu-west-1.compute.internal' #- CM IP is being retrieved despite mentioning ALB - Line 377
        - MEMBER_COORDINATION_HOST: 'ip-10-56-3-137.eu-west-1.compute.internal' #- Line 401
        - DNS_NAME: 'ip-10-56-3-137.eu-west-1.compute.internal' #- Line 1894
        - IP_ADDRESS: '10.56.3.137' #- Line 1903
        - DATABASE_PORT: 23000 #- Line 2253
        - DATABASE_URI: creportdev.cit9nbofg1l2.eu-west-1.rds.amazonaws.com:{{ DATABASE_PORT }}
        - DB_USER: 'db_user' #- Line 2263
        - DB_PWD: 'db_passwd' #- Line 2264
        - SERVICE_NAME: 'creport' #- Line 2272
