- hosts: localhost
  connection: local
  become: true

  #pre_tasks:
  #  - name: Update repositories
  #    apt: 
  #      update_cache: yes
  #    changed_when: false

  tasks:
    #- include: tasks/ansible_setup/create_ansible_user.yml 
    #- include: tasks/ansible_setup/install_cron_package.yml
    #- include: tasks/ansible_setup/add_ansible_to_cron.yml
    #- include: tasks/packages/install_prerequired_package.yml
    #- include: tasks/installation/install_binaries.yml
    #- include: tasks/ec2_setup/set_ulimits.yml
    #  vars:
    #    - user: "root"
    #    - nofile_limit_for: "cog117cm"

    #    install_binaries.yml
    - name: Create variable from command
      command: |
              aws --region eu-west-1 ec2 describe-instances --filters "Name=instance-state-name,Values=running" "Name=instance-id,Values=$(aws ec2 describe-tags --region eu-west-1 --filters "Name=key,Values=AppComponent" "Name=resource-type,Values=instance" "Name=value,Values=analytics"  --query "Tags[*].ResourceId" --output json)" --query 'Reservations[*].Instances[*].[PrivateIpAddress]' --output text | sort | grep -n "10.56.3.237" | cut -d: -f1
      register: command_output
    - debug: msg="{{command_output.stdout}}"
