- name: Play for testing scripts before to move them
  hosts: all
  connection: local
  become: true
  vars:
    - _env: "production"
    - env: "dev"
    - a: "test"

  tasks:
    - name: Play for testing scripts before move them to final files
      ansible.builtin.command: echo "Hello"
      register: my_output
      changed_when: my_output.rc != 0

    - name: Generate Analitycs configuration file.
      ansible.builtin.template:
        src: "./templates/config/test.j2"
        dest: "/tmp/AS1.xml"
        mode: 0644
