#############################################################################################################################
#
#
#############################################################################################################################
- hosts: localhost
  connection: local
  become: true
  vars:
    - component_type: "AS"
    - inst_user: "cog117as"
    - super_user: "root"
    - swap_memory_size: 24
    - aws_region: "eu-west-1"

  tasks:
    # Add /usr/local/lib to path for sudo
    #- include: tasks/ansible_setup/add_lib_to_sudoers_path.yml

    # Add swap memory and activate it
    - include: tasks/ec2_setup/create_swap_memory.yml
      vars:
        swap_size: "{{ swap_memory_size }}"
    
    #
    - include: tasks/ansible_setup/create_ansible_user.yml
    
    # Install base packages
    - include: tasks/packages/install_prerequired_package.yml
    
    #
    - include: tasks/users/create_user.yml
      vars:
        username: "{{ inst_user }}"
    
    #
    - include: tasks/ec2_setup/set_ulimits.yml
      vars:
        - user: "{{ super_user}}"
        - nofile_limit_for: "{{ inst_user }}"
    
    #
    - include: tasks/installation/install_binaries_AS.yml
      vars:
        - root_folder: "/opt"
        - app_folder: "{{ root_folder }}/appl"
        - sources_folder: "{{ app_folder }}/sources"
        - drivers_folder: "{{ app_folder }}/{{ inst_user }}/drivers"
        - configuration_folder: "{{ app_folder }}/{{ inst_user }}/configuration"
        - s3_bucket: "s3://creport-dev-s3-mgt"
        - s3_bucket_with_sources: "{{ s3_bucket }}/Cognos-src"
        - s3_bucket_configuration_files: "{{ s3_bucket_with_sources }}/ConfigFiles"
