- name: Playbook to apply templates
  hosts: localhost
  connection: local
  become: true
  vars:
    - _env: "production"
    - env: "dev"
    - a: "test"


  tasks:
    - name: Play for testing scripts before move them to final files
      ansible.builtin.command: echo "Hello"
      register: my_output
      changed_when: my_output.rc != 0

    - name: Call template include
      ansible.builtin.include_tasks: tasks/installation/apply_template.yml
      vars:
        - var_1: 'var1'
        - var_2: 'var2'
