---
- name: Play testing ansible scripts
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Play for testing scripts before move them to final files
      ansible.builtin.command: echo "Hello"
      register: my_output
      changed_when: my_output.rc != 0

    - name: Generate ntp configuration file.
      ansible.builtin.template:
        src: "./templates/config/test.j2"
        dest: "/tmp/AS1.xml"
        mode: 0644
