- name: Create a directory for application
  ansible.builtin.file:
    path: /opt/appl
    state: directory
    owner: root
    group: root
    mode: '0755'

    #- name: Create a directory for application
    #ansible.builtin.file:
    #path: /opt/appl/cog117cm
    #state: directory
    #owner: cog117cm
    #group: cog117cm
    #mode: '0755'

    #- name: Create a directory for application
    #ansible.builtin.file:
    #path: /opt/appl/cog117as
    #state: directory
    #owner: cog117as
    #group: cog117as
    #mode: '0755'

- name: Create a directory for application
  ansible.builtin.file:
    path: /opt/appl/sources
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy analytic installer from s3
  command: "aws s3 cp {{ item }} ."
  args:
    chdir: "/opt/appl/sources"
  with/items:
  - "s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/analytics-installer-2.2.16-linuxx86.bin"
  - "s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/analytics-installer-2.2.16-linuxx86.bin"
    #- name: Copy sources from S3
    #shell: aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/casrv-11.1.7-2205311318-linuxi38664h.zip .
    #args:
    #chdir: /opt/appl/sources

      #- file:
      #path: /opt/appl/sources/analytics-installer-2.2.16-linuxx86.bin 
      #owner: root 
      #group: root
      #mode: 0777

#shell: aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/analytics-installer-2.2.16-linuxx86.bin .
