- name: Create a directory for application
  ansible.builtin.file:
    path: /opt/appl
    state: directory
    owner: root
    group: root
    mode: '0755'

    #- name: Create a directory for application
    #ansible.builtin.file:
    #path: /opt/appl/cog117cm
    #state: directory
    #owner: cog117cm
    #group: cog117cm
    #mode: '0755'

    #- name: Create a directory for application
    #ansible.builtin.file:
    #path: /opt/appl/cog117as
    #state: directory
    #owner: cog117as
    #group: cog117as
    #mode: '0755'

- name: Create a directory for application
  ansible.builtin.file:
    path: /opt/appl/sources
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy analytic installer from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"
  args: 
    chdir: "/opt/appl/sources"

- file:
    path: "/opt/appl/sources/{{ item }}"
    owner: root 
    group: root
    mode: 0777
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"

- name: Copy properties files from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/Responsefiles/{{ item }} ."
  with_items:
    - "CMInstall.properties"
    - "ASInstall.properties"
    - "GWInstall.properties"
  args:
    chdir: "/opt/appl/sources"


- name: Run Analytics installer for content manager
  shell: "./analytics-installer-2.2.16-linuxx86.bin -f /appl/sources/CMInstall.properties -i silent"
  become_user: cog117cm

- name: Run Analytics installer for application server
  shell: "./analytics-installer-2.2.16-linuxx86.bin -f /appl/sources/ASInstall.properties -i silent"
  become_user: cog117as

- name: Run Analytics installer for Gateway
  shell: "./analytics-installer-2.2.16-linuxx86.bin -f /appl/sources/GWInstall.properties -i silent"
  become_user: cog117gw

- name: Create a directory for drivers
  ansible.builtin.file:
    path: /opt/appl/cog117cm/drivers
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy drivers files from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  with_items:
    - "ojdbc8.jar"
  args:
    chdir: "/opt/appl/cog117cm/drivers"
