- name: Create a directory for application
  ansible.builtin.file:
    path: /appl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create a directory for application
  ansible.builtin.file:
    path: /appl/cog117cm
    state: directory
    owner: root
    group: root
    mode: '0755'
