- name: Create a directory for application
  ansible.builtin.file:
    path: "/opt/appl"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create a directory for application
  ansible.builtin.file:
    path: "/opt/appl/cog117as"
    state: "directory"
    owner: "cog117as"
    group: "cog117as"
    mode: "0755"

- name: Create a directory for application
  ansible.builtin.file:
    path: "/opt/appl/sources"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Copy analytic installer from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"
  args: 
    chdir: "/opt/appl/sources"

- file:
    path: "/opt/appl/sources/{{ item }}"
    owner: "root" 
    group: "root"
    mode: "0777"
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"

- name: Copy properties files from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/Responsefiles/{{ item }} ."
  with_items:
    - "ASInstall.properties"
  args:
    chdir: "/opt/appl/sources"


    #- name: Run Analytics installer for application server
    #shell: "./analytics-installer-2.2.16-linuxx86.bin -f /opt/appl/sources/ASInstall.properties -i silent"
    #args:
    #chdir: "/opt/appl/sources/"
    #become_user: "cog117as"

- name: Create a directory for drivers
  ansible.builtin.file:
    path: "/opt/appl/cog117as/drivers"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Copy drivers files from s3
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  with_items:
    - "ojdbc8.jar"
  args:
    chdir: "/opt/appl/cog117as/drivers"

- name: Copy the Config file from S3 bucket to /appl/co117as/configuration/
  shell: "aws s3 cp s3://cognos-dev-s3-management/Cognos-src/ConfigFiles/AS1Config.xml /opt/appl/cog117as/configuration/cogstartup.xml"

- name: Take a backup of cogstartup.xml in the path /opt/appl/cog117as/configuration
  copy:
    src: "/opt/appl/cog117as/configuration/cogstartup.xml"
    dest: "/opt/appl/cog117as/configuration/cogstartup.xml.bkp"
    owner: "cog117as" 
    group: "cog117as"
    mode: 0644
    #delegate_to: "localhost"
