- name: Variable definition
  vars:
    - var1: "Thanks Rakesh"


- name: Create a directory for application for "{{ inst_user }} {{ var1 }}" 
  file:
    path: "/opt/appl"
    state: "directory"
    owner: "{{ super_user }}"
    group: "{{ super_user }}"
    mode: "0755"

- name: Create a directory for application
  ansible.builtin.file:
    path: "/opt/appl/{{ inst_user }}"
    state: "directory"
    owner: "{{ inst_user }}"
    group: "{{ inst_user }}"
    mode: "0755"

- name: Create a directory for application
  ansible.builtin.file:
    path: "/opt/appl/sources"
    state: "directory"
    owner: "{{ super_user }}"
    group: "{{ super_user }}"
    mode: "0755"

- name: Copy analytic installer from s3
  shell: "/usr/local/bin/aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"
  args: 
    chdir: "/opt/appl/sources"
  become_user: "{{ super_user }}"

- file:
    path: "/opt/appl/sources/{{ item }}"
    owner: "{{ super_user }}" 
    group: "{{ super_user }}"
    mode: "0777"
  with_items:
    - "analytics-installer-2.2.16-linuxx86.bin"
    - "casrv-11.1.7-2205311318-linuxi38664h.zip"

- name: Copy properties files from s3
  shell: "/usr/local/bin/aws s3 cp s3://cognos-dev-s3-management/Cognos-src/Responsefiles/{{ item }} ."
  with_items:
    - "ASInstall.properties"
  args:
    chdir: "/opt/appl/sources"
  become_user: "{{ super_user }}"


  #- name: Run Analytics installer for application server
  #shell: "./analytics-installer-2.2.16-linuxx86.bin -f /opt/appl/sources/ASInstall.properties -i silent"
  #args:
  #  chdir: "/opt/appl/sources/"
  #become_user: "{{ inst_user }}"

- name: Create a directory for drivers
  ansible.builtin.file:
    path: "/opt/appl/{{ inst_user }}/drivers"
    state: "directory"
    owner: "{{ super_user }}"
    group: "{{ super_user }}"
    mode: "0755"

- name: Copy drivers files from s3
  shell: "/usr/local/bin/aws s3 cp s3://cognos-dev-s3-management/Cognos-src/11.1.7FP5/{{ item }} ."
  args:
    chdir: "/opt/appl/{{ inst_user }}/drivers"
  with_items:
    - "ojdbc8.jar"

- name: Copy the Config file from S3 bucket to /appl/co117as/configuration/
  shell: "/usr/local/bin/aws s3 cp s3://cognos-dev-s3-management/Cognos-src/ConfigFiles/AS1Config.xml /opt/appl/{{ inst_user }}/configuration/cogstartup.xml"


- name: Set up owner and permissions for copied files      
  file: 
    path: "{{ item }}"
    owner: "{{ inst_user }}"
    group: "{{ inst_user }}"
  with_items:
    - "/opt/appl/{{ inst_user }}/drivers/ojdbc8.jar"
    - "/opt/appl/{{ inst_user }}/configuration/cogstartup.xml"

- name: Take a backup of cogstartup.xml in the path /opt/appl/{{ inst_user }}/configuration
  copy:
    src: "/opt/appl/{{ inst_user }}/configuration/cogstartup.xml"
    dest: "/opt/appl/{{ inst_user }}/configuration/cogstartup.xml.bkp"
    owner: "{{ inst_user }}"
    group: "{{ inst_user }}"  
    mode: 0644
