- name: Setting-up nofles and nproc limit for {{ user }} 
  pam_limits:
    domain: "{{ user }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{item.value}}"
    #loop:
  with_items:
    # Add nofile and nproc, both soft and hard, limit for the user db_user with a comment.
    # Type "-" for enforcing both soft and hard resource limits together for more details read `man limits.conf`.
    - { limit_type: '-', limit_item: 'cpu', value: 'unlimited'  }
    - { limit_type: '-', limit_item: 'fsize', value: 'unlimited'  }
    - { limit_type: '-', limit_item: 'nproc', value: 'unlimited'  }
    - { limit_type: '-', limit_item: 'stack', value: 'unlimited'  }
    - { limit_type: '-', limit_item: 'as', value: 'unlimited'  }
    - { limit_type: '-', limit_item: 'rss', value: 'unlimited'  }
- name: reload settings from all system configuration files
  shell: sysctl --system
