- name: Setting-up nofles and nproc limit for db_user
    pam_limits:
      domain: db_user
      limit_type: "{{item.limit_type}}"
      limit_item: "{{item.limit_item}}"
      value: "{{item.value}}"
    loop:
      # Add nofile and nproc, both soft and hard, limit for the user db_user with a comment.
      # Type "-" for enforcing both soft and hard resource limits together for more details read `man limits.conf`.
      - { limit_type: '-', limit_item: 'nofile', value: 260000 }
      - { limit_type: '-', limit_item: 'nproc', value: 16383 }
  with_limit:
    - cpu
    - fsize 
    - nproc
    - stack
    - rss
    - as
